// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: Door.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LockLock int32

const (
	Lock_UNLOCKED LockLock = 0
	Lock_SOFT     LockLock = 1
	Lock_HARD     LockLock = 2
)

// Enum value maps for LockLock.
var (
	LockLock_name = map[int32]string{
		0: "UNLOCKED",
		1: "SOFT",
		2: "HARD",
	}
	LockLock_value = map[string]int32{
		"UNLOCKED": 0,
		"SOFT":     1,
		"HARD":     2,
	}
)

func (x LockLock) Enum() *LockLock {
	p := new(LockLock)
	*p = x
	return p
}

func (x LockLock) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LockLock) Descriptor() protoreflect.EnumDescriptor {
	return file_Door_proto_enumTypes[0].Descriptor()
}

func (LockLock) Type() protoreflect.EnumType {
	return &file_Door_proto_enumTypes[0]
}

func (x LockLock) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LockLock.Descriptor instead.
func (LockLock) EnumDescriptor() ([]byte, []int) {
	return file_Door_proto_rawDescGZIP(), []int{0, 0}
}

type Lock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DoorIsOpen bool     `protobuf:"varint,1,opt,name=doorIsOpen,proto3" json:"doorIsOpen,omitempty"`
	LockStatus LockLock `protobuf:"varint,2,opt,name=lockStatus,proto3,enum=LockLock" json:"lockStatus,omitempty"`
}

func (x *Lock) Reset() {
	*x = Lock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Door_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Lock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lock) ProtoMessage() {}

func (x *Lock) ProtoReflect() protoreflect.Message {
	mi := &file_Door_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lock.ProtoReflect.Descriptor instead.
func (*Lock) Descriptor() ([]byte, []int) {
	return file_Door_proto_rawDescGZIP(), []int{0}
}

func (x *Lock) GetDoorIsOpen() bool {
	if x != nil {
		return x.DoorIsOpen
	}
	return false
}

func (x *Lock) GetLockStatus() LockLock {
	if x != nil {
		return x.LockStatus
	}
	return Lock_UNLOCKED
}

var File_Door_proto protoreflect.FileDescriptor

var file_Door_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x44, 0x6f, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7c, 0x0a, 0x04,
	0x4c, 0x6f, 0x63, 0x6b, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x6f, 0x6f, 0x72, 0x49, 0x73, 0x4f, 0x70,
	0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x64, 0x6f, 0x6f, 0x72, 0x49, 0x73,
	0x4f, 0x70, 0x65, 0x6e, 0x12, 0x2a, 0x0a, 0x0a, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x4c, 0x6f, 0x63, 0x6b, 0x2e,
	0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x0a, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0x28, 0x0a, 0x04, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x0c, 0x0a, 0x08, 0x55, 0x4e, 0x4c, 0x4f,
	0x43, 0x4b, 0x45, 0x44, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x4f, 0x46, 0x54, 0x10, 0x01,
	0x12, 0x08, 0x0a, 0x04, 0x48, 0x41, 0x52, 0x44, 0x10, 0x02, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x6d,
	0x61, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Door_proto_rawDescOnce sync.Once
	file_Door_proto_rawDescData = file_Door_proto_rawDesc
)

func file_Door_proto_rawDescGZIP() []byte {
	file_Door_proto_rawDescOnce.Do(func() {
		file_Door_proto_rawDescData = protoimpl.X.CompressGZIP(file_Door_proto_rawDescData)
	})
	return file_Door_proto_rawDescData
}

var file_Door_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Door_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Door_proto_goTypes = []interface{}{
	(LockLock)(0), // 0: Lock.lock
	(*Lock)(nil),  // 1: Lock
}
var file_Door_proto_depIdxs = []int32{
	0, // 0: Lock.lockStatus:type_name -> Lock.lock
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_Door_proto_init() }
func file_Door_proto_init() {
	if File_Door_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Door_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Lock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Door_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Door_proto_goTypes,
		DependencyIndexes: file_Door_proto_depIdxs,
		EnumInfos:         file_Door_proto_enumTypes,
		MessageInfos:      file_Door_proto_msgTypes,
	}.Build()
	File_Door_proto = out.File
	file_Door_proto_rawDesc = nil
	file_Door_proto_goTypes = nil
	file_Door_proto_depIdxs = nil
}
