// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: protobufferData.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LOCK_STATUSOpenRequest int32

const (
	LOCK_STATUS_NO_REQUEST  LOCK_STATUSOpenRequest = 0
	LOCK_STATUS_APPROVED    LOCK_STATUSOpenRequest = 1
	LOCK_STATUS_DISAPPROVED LOCK_STATUSOpenRequest = 2
)

// Enum value maps for LOCK_STATUSOpenRequest.
var (
	LOCK_STATUSOpenRequest_name = map[int32]string{
		0: "NO_REQUEST",
		1: "APPROVED",
		2: "DISAPPROVED",
	}
	LOCK_STATUSOpenRequest_value = map[string]int32{
		"NO_REQUEST":  0,
		"APPROVED":    1,
		"DISAPPROVED": 2,
	}
)

func (x LOCK_STATUSOpenRequest) Enum() *LOCK_STATUSOpenRequest {
	p := new(LOCK_STATUSOpenRequest)
	*p = x
	return p
}

func (x LOCK_STATUSOpenRequest) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LOCK_STATUSOpenRequest) Descriptor() protoreflect.EnumDescriptor {
	return file_protobufferData_proto_enumTypes[0].Descriptor()
}

func (LOCK_STATUSOpenRequest) Type() protoreflect.EnumType {
	return &file_protobufferData_proto_enumTypes[0]
}

func (x LOCK_STATUSOpenRequest) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LOCK_STATUSOpenRequest.Descriptor instead.
func (LOCK_STATUSOpenRequest) EnumDescriptor() ([]byte, []int) {
	return file_protobufferData_proto_rawDescGZIP(), []int{0, 0}
}

type LOCK_STATUSLock int32

const (
	LOCK_STATUS_UNLOCKED LOCK_STATUSLock = 0
	LOCK_STATUS_SOFT     LOCK_STATUSLock = 1
	LOCK_STATUS_HARD     LOCK_STATUSLock = 2
)

// Enum value maps for LOCK_STATUSLock.
var (
	LOCK_STATUSLock_name = map[int32]string{
		0: "UNLOCKED",
		1: "SOFT",
		2: "HARD",
	}
	LOCK_STATUSLock_value = map[string]int32{
		"UNLOCKED": 0,
		"SOFT":     1,
		"HARD":     2,
	}
)

func (x LOCK_STATUSLock) Enum() *LOCK_STATUSLock {
	p := new(LOCK_STATUSLock)
	*p = x
	return p
}

func (x LOCK_STATUSLock) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LOCK_STATUSLock) Descriptor() protoreflect.EnumDescriptor {
	return file_protobufferData_proto_enumTypes[1].Descriptor()
}

func (LOCK_STATUSLock) Type() protoreflect.EnumType {
	return &file_protobufferData_proto_enumTypes[1]
}

func (x LOCK_STATUSLock) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LOCK_STATUSLock.Descriptor instead.
func (LOCK_STATUSLock) EnumDescriptor() ([]byte, []int) {
	return file_protobufferData_proto_rawDescGZIP(), []int{0, 1}
}

type Door_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DoorRequest LOCK_STATUSOpenRequest `protobuf:"varint,1,opt,name=doorRequest,proto3,enum=LOCK_STATUSOpenRequest" json:"doorRequest,omitempty"`
	LockStatus  LOCK_STATUSLock        `protobuf:"varint,2,opt,name=lockStatus,proto3,enum=LOCK_STATUSLock" json:"lockStatus,omitempty"`
}

func (x *Door_Request) Reset() {
	*x = Door_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufferData_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Door_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Door_Request) ProtoMessage() {}

func (x *Door_Request) ProtoReflect() protoreflect.Message {
	mi := &file_protobufferData_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Door_Request.ProtoReflect.Descriptor instead.
func (*Door_Request) Descriptor() ([]byte, []int) {
	return file_protobufferData_proto_rawDescGZIP(), []int{0}
}

func (x *Door_Request) GetDoorRequest() LOCK_STATUSOpenRequest {
	if x != nil {
		return x.DoorRequest
	}
	return LOCK_STATUS_NO_REQUEST
}

func (x *Door_Request) GetLockStatus() LOCK_STATUSLock {
	if x != nil {
		return x.LockStatus
	}
	return LOCK_STATUS_UNLOCKED
}

type RFID_MESSAGE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RFID_CODE string `protobuf:"bytes,1,opt,name=RFID_CODE,json=RFIDCODE,proto3" json:"RFID_CODE,omitempty"`
}

func (x *RFID_MESSAGE) Reset() {
	*x = RFID_MESSAGE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufferData_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RFID_MESSAGE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RFID_MESSAGE) ProtoMessage() {}

func (x *RFID_MESSAGE) ProtoReflect() protoreflect.Message {
	mi := &file_protobufferData_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RFID_MESSAGE.ProtoReflect.Descriptor instead.
func (*RFID_MESSAGE) Descriptor() ([]byte, []int) {
	return file_protobufferData_proto_rawDescGZIP(), []int{1}
}

func (x *RFID_MESSAGE) GetRFID_CODE() string {
	if x != nil {
		return x.RFID_CODE
	}
	return ""
}

var File_protobufferData_proto protoreflect.FileDescriptor

var file_protobufferData_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x44, 0x61, 0x74,
	0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe4, 0x01, 0x0a, 0x0b, 0x4c, 0x4f, 0x43, 0x4b,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x12, 0x3a, 0x0a, 0x0b, 0x64, 0x6f, 0x6f, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x4c,
	0x4f, 0x43, 0x4b, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0b, 0x64, 0x6f, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x0a, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x4c, 0x4f, 0x43, 0x4b, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x55, 0x53, 0x2e, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x0a, 0x6c, 0x6f, 0x63, 0x6b,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x3c, 0x0a, 0x0b, 0x6f, 0x70, 0x65, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x0a, 0x4e, 0x4f, 0x5f, 0x52, 0x45, 0x51, 0x55,
	0x45, 0x53, 0x54, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x50, 0x50, 0x52, 0x4f, 0x56, 0x45,
	0x44, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x44, 0x49, 0x53, 0x41, 0x50, 0x50, 0x52, 0x4f, 0x56,
	0x45, 0x44, 0x10, 0x02, 0x22, 0x28, 0x0a, 0x04, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x0c, 0x0a, 0x08,
	0x55, 0x4e, 0x4c, 0x4f, 0x43, 0x4b, 0x45, 0x44, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x4f,
	0x46, 0x54, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x41, 0x52, 0x44, 0x10, 0x02, 0x22, 0x2b,
	0x0a, 0x0c, 0x52, 0x46, 0x49, 0x44, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x12, 0x1b,
	0x0a, 0x09, 0x52, 0x46, 0x49, 0x44, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x52, 0x46, 0x49, 0x44, 0x43, 0x4f, 0x44, 0x45, 0x42, 0x07, 0x5a, 0x05, 0x2e,
	0x6d, 0x61, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobufferData_proto_rawDescOnce sync.Once
	file_protobufferData_proto_rawDescData = file_protobufferData_proto_rawDesc
)

func file_protobufferData_proto_rawDescGZIP() []byte {
	file_protobufferData_proto_rawDescOnce.Do(func() {
		file_protobufferData_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobufferData_proto_rawDescData)
	})
	return file_protobufferData_proto_rawDescData
}

var file_protobufferData_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protobufferData_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobufferData_proto_goTypes = []interface{}{
	(LOCK_STATUSOpenRequest)(0), // 0: Door_Request.openRequest
	(LOCK_STATUSLock)(0),        // 1: Door_Request.lock
	(*Door_Request)(nil),        // 2: Door_Request
	(*RFID_MESSAGE)(nil),        // 3: RFID_MESSAGE
}
var file_protobufferData_proto_depIdxs = []int32{
	0, // 0: Door_Request.doorRequest:type_name -> Door_Request.openRequest
	1, // 1: Door_Request.lockStatus:type_name -> Door_Request.lock
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protobufferData_proto_init() }
func file_protobufferData_proto_init() {
	if File_protobufferData_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobufferData_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Door_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufferData_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RFID_MESSAGE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobufferData_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobufferData_proto_goTypes,
		DependencyIndexes: file_protobufferData_proto_depIdxs,
		EnumInfos:         file_protobufferData_proto_enumTypes,
		MessageInfos:      file_protobufferData_proto_msgTypes,
	}.Build()
	File_protobufferData_proto = out.File
	file_protobufferData_proto_rawDesc = nil
	file_protobufferData_proto_goTypes = nil
	file_protobufferData_proto_depIdxs = nil
}
