// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: protobufferData.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Door_RequestOpenRequest int32

const (
	Door_Request_REQUEST_NOT_SET Door_RequestOpenRequest = 0
	Door_Request_NO_REQUEST      Door_RequestOpenRequest = 1
	Door_Request_APPROVED        Door_RequestOpenRequest = 2
	Door_Request_DISAPPROVED     Door_RequestOpenRequest = 3
)

// Enum value maps for Door_RequestOpenRequest.
var (
	Door_RequestOpenRequest_name = map[int32]string{
		0: "REQUEST_NOT_SET",
		1: "NO_REQUEST",
		2: "APPROVED",
		3: "DISAPPROVED",
	}
	Door_RequestOpenRequest_value = map[string]int32{
		"REQUEST_NOT_SET": 0,
		"NO_REQUEST":      1,
		"APPROVED":        2,
		"DISAPPROVED":     3,
	}
)

func (x Door_RequestOpenRequest) Enum() *Door_RequestOpenRequest {
	p := new(Door_RequestOpenRequest)
	*p = x
	return p
}

func (x Door_RequestOpenRequest) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Door_RequestOpenRequest) Descriptor() protoreflect.EnumDescriptor {
	return file_protobufferData_proto_enumTypes[0].Descriptor()
}

func (Door_RequestOpenRequest) Type() protoreflect.EnumType {
	return &file_protobufferData_proto_enumTypes[0]
}

func (x Door_RequestOpenRequest) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Door_RequestOpenRequest.Descriptor instead.
func (Door_RequestOpenRequest) EnumDescriptor() ([]byte, []int) {
	return file_protobufferData_proto_rawDescGZIP(), []int{0, 0}
}

type Door_RequestLock int32

const (
	Door_Request_LOCK_NOT_SET Door_RequestLock = 0
	Door_Request_UNLOCKED     Door_RequestLock = 1
	Door_Request_SOFT         Door_RequestLock = 2
	Door_Request_HARD         Door_RequestLock = 3
)

// Enum value maps for Door_RequestLock.
var (
	Door_RequestLock_name = map[int32]string{
		0: "LOCK_NOT_SET",
		1: "UNLOCKED",
		2: "SOFT",
		3: "HARD",
	}
	Door_RequestLock_value = map[string]int32{
		"LOCK_NOT_SET": 0,
		"UNLOCKED":     1,
		"SOFT":         2,
		"HARD":         3,
	}
)

func (x Door_RequestLock) Enum() *Door_RequestLock {
	p := new(Door_RequestLock)
	*p = x
	return p
}

func (x Door_RequestLock) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Door_RequestLock) Descriptor() protoreflect.EnumDescriptor {
	return file_protobufferData_proto_enumTypes[1].Descriptor()
}

func (Door_RequestLock) Type() protoreflect.EnumType {
	return &file_protobufferData_proto_enumTypes[1]
}

func (x Door_RequestLock) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Door_RequestLock.Descriptor instead.
func (Door_RequestLock) EnumDescriptor() ([]byte, []int) {
	return file_protobufferData_proto_rawDescGZIP(), []int{0, 1}
}

type Door_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DoorRequest Door_RequestOpenRequest `protobuf:"varint,1,opt,name=doorRequest,proto3,enum=Door_RequestOpenRequest" json:"doorRequest,omitempty"`
	LockStatus  Door_RequestLock        `protobuf:"varint,2,opt,name=lockStatus,proto3,enum=Door_RequestLock" json:"lockStatus,omitempty"`
}

func (x *Door_Request) Reset() {
	*x = Door_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufferData_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Door_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Door_Request) ProtoMessage() {}

func (x *Door_Request) ProtoReflect() protoreflect.Message {
	mi := &file_protobufferData_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Door_Request.ProtoReflect.Descriptor instead.
func (*Door_Request) Descriptor() ([]byte, []int) {
	return file_protobufferData_proto_rawDescGZIP(), []int{0}
}

func (x *Door_Request) GetDoorRequest() Door_RequestOpenRequest {
	if x != nil {
		return x.DoorRequest
	}
	return Door_Request_REQUEST_NOT_SET
}

func (x *Door_Request) GetLockStatus() Door_RequestLock {
	if x != nil {
		return x.LockStatus
	}
	return Door_Request_LOCK_NOT_SET
}

var File_protobufferData_proto protoreflect.FileDescriptor

var file_protobufferData_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x44, 0x61, 0x74,
	0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8e, 0x02, 0x0a, 0x0c, 0x44, 0x6f, 0x6f, 0x72,
	0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x0b, 0x64, 0x6f, 0x6f, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e,
	0x44, 0x6f, 0x6f, 0x72, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x6f, 0x70, 0x65,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0b, 0x64, 0x6f, 0x6f, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x0a, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x44, 0x6f, 0x6f, 0x72,
	0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x0a, 0x6c,
	0x6f, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x51, 0x0a, 0x0b, 0x6f, 0x70, 0x65,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x13, 0x0a, 0x0f, 0x52, 0x45, 0x51, 0x55,
	0x45, 0x53, 0x54, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x53, 0x45, 0x54, 0x10, 0x00, 0x12, 0x0e, 0x0a,
	0x0a, 0x4e, 0x4f, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x10, 0x01, 0x12, 0x0c, 0x0a,
	0x08, 0x41, 0x50, 0x50, 0x52, 0x4f, 0x56, 0x45, 0x44, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x44,
	0x49, 0x53, 0x41, 0x50, 0x50, 0x52, 0x4f, 0x56, 0x45, 0x44, 0x10, 0x03, 0x22, 0x3a, 0x0a, 0x04,
	0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x10, 0x0a, 0x0c, 0x4c, 0x4f, 0x43, 0x4b, 0x5f, 0x4e, 0x4f, 0x54,
	0x5f, 0x53, 0x45, 0x54, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x55, 0x4e, 0x4c, 0x4f, 0x43, 0x4b,
	0x45, 0x44, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x4f, 0x46, 0x54, 0x10, 0x02, 0x12, 0x08,
	0x0a, 0x04, 0x48, 0x41, 0x52, 0x44, 0x10, 0x03, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x6d, 0x61, 0x69,
	0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobufferData_proto_rawDescOnce sync.Once
	file_protobufferData_proto_rawDescData = file_protobufferData_proto_rawDesc
)

func file_protobufferData_proto_rawDescGZIP() []byte {
	file_protobufferData_proto_rawDescOnce.Do(func() {
		file_protobufferData_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobufferData_proto_rawDescData)
	})
	return file_protobufferData_proto_rawDescData
}

var file_protobufferData_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protobufferData_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protobufferData_proto_goTypes = []interface{}{
	(Door_RequestOpenRequest)(0), // 0: Door_Request.openRequest
	(Door_RequestLock)(0),        // 1: Door_Request.lock
	(*Door_Request)(nil),         // 2: Door_Request
}
var file_protobufferData_proto_depIdxs = []int32{
	0, // 0: Door_Request.doorRequest:type_name -> Door_Request.openRequest
	1, // 1: Door_Request.lockStatus:type_name -> Door_Request.lock
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protobufferData_proto_init() }
func file_protobufferData_proto_init() {
	if File_protobufferData_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobufferData_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Door_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobufferData_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobufferData_proto_goTypes,
		DependencyIndexes: file_protobufferData_proto_depIdxs,
		EnumInfos:         file_protobufferData_proto_enumTypes,
		MessageInfos:      file_protobufferData_proto_msgTypes,
	}.Build()
	File_protobufferData_proto = out.File
	file_protobufferData_proto_rawDesc = nil
	file_protobufferData_proto_goTypes = nil
	file_protobufferData_proto_depIdxs = nil
}
