// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "AGPL V3",
            "url": "https://www.gnu.org/licenses/agpl-3.0.en.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/getInitData": {
            "get": {
                "description": "Gets the currents users claim the name that is associated with it and check the status of the Protobuffer package",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "root"
                ],
                "summary": "Returns the current users name and the lock status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": ""
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "If the user is found in the database the server returns a JWT token, which is used to access the other APIs",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "root"
                ],
                "summary": "Handles the authentication of the users.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Password",
                        "name": "password",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": ""
                    }
                }
            }
        },
        "/manualOpen": {
            "put": {
                "description": "When the lock state of the device is set to hard, the door can only be opened manually from the interface",
                "consumes": [
                    "*/*"
                ],
                "tags": [
                    "root"
                ],
                "summary": "Commands the embedded device to open the door",
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/statistics/keycardUsed": {
            "get": {
                "description": "Queries the ArangoDB for RFID history and returns results as JSON",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "root"
                ],
                "summary": "Returns the date when the RFID card was read",
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/statistics/modeChanged": {
            "get": {
                "description": "Queries the ArangoDB for lock history and returns results as JSON",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "root"
                ],
                "summary": "Returns the date when the lock mode was changed",
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/updateLock/": {
            "put": {
                "description": "User sets the wanted lock mode from the interface",
                "consumes": [
                    "*/*"
                ],
                "tags": [
                    "root"
                ],
                "summary": "Set the lock mode",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Set lock Mode",
                        "name": "?",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:8080",
	BasePath:    "/",
	Schemes:     []string{"http"},
	Title:       "IoT Door Controller Project",
	Description: "User interface for handling the locking of the door.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
